// NEWS 
export const NEWS_STORE_NAME = 'NEWS_STORE'
export const FETCH_NEWS_DATA = 'FETCH_NEWS_DATA'
export const FETCH_NEWS_IN_PROGRSS = 'FETCH_NEWS_IN_PROGRESS'
export const FETCH_NEW_HAS_ERROR = 'FETCH_NEW_HAS_ERROR'

// FLASH
export const FLASH_ERROR = 'FLASH_ERROR'
export const FLASH_SUCCESS = 'FLASH_SUCCESS'
export const FLASH_WARN = 'FLASH_WARN'
